# Author Casta-mere
name: Build & Release

on:
  push:
    tags:
      - "V*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare generated directory
        run: mkdir -p generated

      - name: Insert VERSION into script
        run: |
          VERSION="${{ github.ref_name }}"
          echo "# $VERSION" > generated/fzf-scripts.sh


      - name: 合并脚本 fzf-scripts.sh
        run: |
          awk 'FNR==1 && NR>1 {print ""} 1' *.sh > generated/fzf-scripts.sh
          chmod +x generated/fzf-scripts.sh

      - name: 准备安装脚本
        run: |
          cp ./install/install.sh generated/
          chmod +x generated/install.sh

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            generated/*
        env:
          GITHUB_TOKEN: ${{ secrets.FZF }}